apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-http
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
