apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-0-external
  labels:
    app: elasticsearch
spec:
  type: NodePort
  selector:
    app: elasticsearch
    statefulset.kubernetes.io/pod-name: elasticsearch-0
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      nodePort: 32200
