apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - name: external
      port: 9094
      targetPort: 9094
      nodePort: 30092
