apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-external
  labels:
    app: elasticsearch
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      nodePort: 32200
    - name: transport
      port: 9300
      targetPort: 9300
      nodePort: 32300
