apiVersion: v1
kind: Service
metadata:
  name: kibana-0-external
  labels:
    app: kibana
spec:
  type: NodePort
  selector:
    app: kibana
    statefulset.kubernetes.io/pod-name: kibana-0
  ports:
    - name: http
      port: 5601
      targetPort: 5601
      nodePort: 32323
